// frontend_angular/src/app/features/dashboard/dashboard.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { MatDividerModule } from '@angular/material/divider';
import { MatButtonModule } from '@angular/material/button';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { HealthData, UserService } from '../../core/services/user.service';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatIconModule,
    MatDividerModule,
    MatButtonModule,
    MatProgressSpinnerModule,
  ],
  templateUrl: './dashboard.component.html',
  styleUrl: './dashboard.component.css',
})
export class DashboardComponent implements OnInit {
  private readonly userService = inject(UserService);

  healthData: HealthData | null = null;
  loading = false;

  ngOnInit(): void {
    this.checkHealth();
  }

  checkHealth(): void {
    this.loading = true;
    this.userService.healthCheck().subscribe({
      next: (res) => {
        this.healthData = res.data;
        this.loading = false;
      },
      error: (err) => {
        this.healthData = null;
        this.loading = false;
      },
    });
  }
}

<div class="home-container">
  <div class="row">
    <div class="col">
      <mat-card appearance="raised">
        <mat-card-header>
          <mat-card-title class="card-header">
            <mat-icon inline style="font-size: 28px; width: 28px; height: 28px;">dvr</mat-icon>
            <span>Welcome to your Dashboard</span>
          </mat-card-title>
        </mat-card-header>
        <mat-card-content>
          <p class="description">
            This is a full-stack demo project built with {{ healthData?.sysinfo }} backend
            and Angular 21.2.20 + TypeScript + Element Plus frontend.
          </p>
          <mat-divider></mat-divider>
          <table class="tech-table">
            <caption>Tech Stack</caption>
            <tbody>
              <tr>
                <th>Backend</th><td colspan="3">{{ healthData?.sysinfo }}</td>
                <!-- <th>Java Version</th><td>21</td> -->
              </tr>
              <tr>
                <th>Frontend</th><td>Anguar 21.2.20</td>
                <th>UI Library</th><td>Element Plus 2.7</td>
              </tr>
              <tr>
                <th>Language</th><td>TypeScript 5.4</td>
                <th>Build Tool</th><td>Vite 5.2</td>
              </tr>
            </tbody>
          </table>
        </mat-card-content>
      </mat-card>

      <mat-card appearance="raised" style="margin-top: 20px">
        <mat-card-header>
          <mat-card-title class="card-header">
            <mat-icon inline style="font-size: 28px; width: 28px; height: 28px;">cable</mat-icon>
            <span>Backend Health Status</span>
          </mat-card-title>
        </mat-card-header>
        <mat-card-content>
          <div *ngIf="loading" style="text-align: center">
            <mat-spinner diameter="32" style="margin: 0 auto"></mat-spinner>
            <p>Checking backend status...</p>
          </div>

          <div *ngIf="!loading && healthData" class="result" [class.result-success]="healthData.status === 'UP'" [class.result-error]="healthData.status !== 'UP'">
            <mat-icon class="result-icon">{{ healthData.status === 'UP' ? 'check_circle' : 'cancel' }}</mat-icon>
            <h3>{{ healthData.status === 'UP' ? 'Backend is running' : 'Backend is down' }}</h3>
            <p>Service: {{ healthData.service }} | Timestamp: {{ healthData.timestamp }}</p>
          </div>

          <div *ngIf="!loading && !healthData" class="result result-warning">
            <mat-icon class="result-icon">warning</mat-icon>
            <h3>Cannot connect to backend</h3>
            <p>Make sure the Spring Boot server is running on port 8080</p>
          </div>

          <div style="text-align: center; margin-top: 10px">
            <button mat-raised-button color="primary" (click)="checkHealth()" [disabled]="loading">
              <mat-icon>refresh</mat-icon>
              Refresh Status
            </button>
          </div>
        </mat-card-content>
      </mat-card>
    </div>
  </div>
</div>

// frontend_nextjs/src/app/dashboard/page.tsx
'use client'

import { useCallback, useEffect, useState } from 'react'
import { Button, Card, Col, Descriptions, Divider, Result, Row, Spin } from 'antd'
import { ApiOutlined, DesktopOutlined, ReloadOutlined } from '@ant-design/icons'
import { healthCheck } from '@/lib/api'

interface HealthData {
  status: string
  timestamp: string
  service: string
  sysinfo: string
}

export default function DashboardPage() {
  const [healthData, setHealthData] = useState<HealthData | null>(null)
  const [loading, setLoading] = useState(false)

  const checkHealth = useCallback(async () => {
    setLoading(true)
    try {
      const res = await healthCheck()
      setHealthData(res.data)
    } catch {
      setHealthData(null)
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    checkHealth()
  }, [checkHealth])

  return (
    <div className="home-container">
      <Row gutter={20} justify="center">
        <Col span={16}>
          <Card
            hoverable
            title={
              <div className="card-header">
                <DesktopOutlined style={{ fontSize: 28 }} />
                <span>Welcome to your Dashboard</span>
              </div>
            }
          >
            <p className="description">
              This is a full-stack demo project built with { healthData?.sysinfo ?? "(N/A)" } backend
              and Next.js + TypeScript + Ant Design frontend.
            </p>
            <Divider />
            <Descriptions title="Tech Stack" column={2} bordered>
              <Descriptions.Item label="Backend" span={2}>{ healthData?.sysinfo ?? "(N/A)" }</Descriptions.Item>
              {/* <Descriptions.Item label="Java Version">25</Descriptions.Item> */}
              <Descriptions.Item label="Frontend">Next.js (App Router)</Descriptions.Item>
              <Descriptions.Item label="UI Library">Ant Design 5</Descriptions.Item>
              <Descriptions.Item label="Language">TypeScript 5.4</Descriptions.Item>
              <Descriptions.Item label="Architecture">Backend-for-Frontend (BFF)</Descriptions.Item>
            </Descriptions>
          </Card>

          <Card
            hoverable
            style={{ marginTop: 20 }}
            title={
              <div className="card-header">
                <ApiOutlined style={{ fontSize: 28 }} />
                <span>Backend Health Status</span>
              </div>
            }
          >
            {loading ? (
              <div style={{ textAlign: 'center' }}>
                <Spin size="large" />
                <p>Checking backend status...</p>
              </div>
            ) : healthData ? (
              <Result
                status={healthData.status === 'UP' ? 'success' : 'error'}
                title={healthData.status === 'UP' ? 'Backend is running' : 'Backend is down'}
                subTitle={`Service: ${healthData.service} | Timestamp: ${healthData.timestamp}`}
              />
            ) : (
              <Result
                status="warning"
                title="Cannot connect to backend"
                subTitle="Make sure the server is running on port 8080"
              />
            )}
            <div style={{ textAlign: 'center', marginTop: 10 }}>
              <Button type="primary" icon={<ReloadOutlined />} loading={loading} onClick={checkHealth}>
                Refresh Status
              </Button>
            </div>
          </Card>
        </Col>
      </Row>
    </div>
  )
}
