// frontend_vue/src/views/HomeView.vue
<template>
  <div class="home-container">
    <el-row :gutter="20" justify="center">
      <el-col :span="16">
        <el-card shadow="hover">
          <template #header>
            <div class="card-header">
              <el-icon :size="28"><Monitor /></el-icon>
              <span>Welcome to Spring Boot App</span>
            </div>
          </template>
          <p class="description">
            Full-stack demo project built with Spring Boot 3.x (Java 21) backend
            and Vue 3 + TypeScript + Element Plus frontend.
          </p>
          <el-divider />
          <el-descriptions title="Tech Stack" :column="2" border>
            <el-descriptions-item label="Backend">Spring Boot 3.2.5</el-descriptions-item>
            <el-descriptions-item label="Java Version">21</el-descriptions-item>
            <el-descriptions-item label="Frontend">Vue 3.4</el-descriptions-item>
            <el-descriptions-item label="UI Library">Element Plus 2.7</el-descriptions-item>
            <el-descriptions-item label="Language">TypeScript 5.4</el-descriptions-item>
            <el-descriptions-item label="Build Tool">Vite 5.2</el-descriptions-item>
          </el-descriptions>
        </el-card>
      </el-col>
    </el-row>
  </div>
</template>

<style scoped>
.home-container {
  padding: 20px;
}

.card-header {
  display: flex;
  align-items: center;
  gap: 10px;
  font-size: 18px;
  font-weight: bold;
}

.description {
  font-size: 16px;
  line-height: 1.8;
  color: #606266;
}
</style>

// frontend_react/src/views/HomeView.tsx
import { useCallback, useEffect, useState } from 'react'
import { Card, Col, Descriptions, Divider, Row } from 'antd'
import { DesktopOutlined } from '@ant-design/icons'
import { healthCheck } from '@/api/user'

interface HealthData {
  status: string
  timestamp: string
  service: string
  sysinfo: string
}

function HomeView() {
  const [healthData, setHealthData] = useState<HealthData | null>(null)

  const checkHealth = useCallback(async () => {
    try {
      const res = await healthCheck()
      setHealthData(res.data)
    } catch {
      setHealthData(null)
    }
  }, [])

  useEffect(() => {
    checkHealth()
  }, [checkHealth])

  return (
    <div className="home-container">
      <Row gutter={20} justify="center">
        <Col span={16}>
          <Card
            hoverable
            title={
              <div className="card-header">
                <DesktopOutlined style={{ fontSize: 28 }} />
                <span>Welcome to Spring Boot App</span>
              </div>
            }
          >
            <p className="description">
              Full-stack demo project built with { healthData?.sysinfo ?? "(N/A)" } backend
              and React 18 + TypeScript + Ant Design frontend.
            </p>
            <Divider />
            <Descriptions title="Tech Stack" column={2} bordered>
              <Descriptions.Item label="Backend" span={2}>{ healthData?.sysinfo ?? "(N/A)" }</Descriptions.Item>
              {/* <Descriptions.Item label="Java Version">25</Descriptions.Item> */}
              <Descriptions.Item label="Frontend">React 18</Descriptions.Item>
              <Descriptions.Item label="UI Library">Ant Design 5</Descriptions.Item>
              <Descriptions.Item label="Language">TypeScript 5.4</Descriptions.Item>
              <Descriptions.Item label="Build Tool">Vite 5.2</Descriptions.Item>
            </Descriptions>
          </Card>
        </Col>
      </Row>
    </div>
  )
}

export default HomeView
