// frontend_react/src/App.tsx
import { useEffect, useState } from 'react'
import { Link, Outlet, useLocation, useNavigate } from 'react-router-dom'
import { ConfigProvider, Layout, Menu } from 'antd'
import type { MenuProps } from 'antd'
import { DesktopOutlined, HomeFilled, UserOutlined } from '@ant-design/icons'
import enUS from 'antd/locale/en_US'

const { Header, Content } = Layout

function App() {
  const location = useLocation()
  const navigate = useNavigate()
  const [isLoggedIn, setIsLoggedIn] = useState(false)

  // Function to check local storage auth status
  function checkAuthStatus() {
    setIsLoggedIn(!!localStorage.getItem('token'))
  }

  // Check status when app initializes, and again whenever the route changes
  // to automatically recalculate the login state (mirrors the Vue `watch(route.path)`).
  useEffect(() => {
    checkAuthStatus()
  }, [location.pathname])

  // Global logout method
  function logout() {
    localStorage.removeItem('token')
    setIsLoggedIn(false)
    navigate('/login')
  }

  const items: MenuProps['items'] = [
    { key: '/', icon: <HomeFilled />, label: <Link to="/">Home</Link> },
    !isLoggedIn && { key: '/login', icon: <HomeFilled />, label: <Link to="/login">Login</Link> },
    isLoggedIn && { key: '/dashboard', icon: <UserOutlined />, label: <Link to="/dashboard">Dashboard</Link> },
    isLoggedIn && { key: '/users', icon: <UserOutlined />, label: <Link to="/users">Users</Link> },
    isLoggedIn && { key: '/logout', icon: <UserOutlined />, label: 'Log Out' },
  ].filter(Boolean) as MenuProps['items']

  return (
    <ConfigProvider locale={enUS}
      theme={{
        token: {  // Default background color: #f5f5f5
          colorBgLayout: '#fff',
        },
        components: {
          Menu: {
            // horizontalItemHoverColor: 'inherit', // Stops text color change (optional)
            // horizontalLineHeight: 'normal',      // Optional adjustment

            // FIX: Overrides the bottom indicator line height/color to hide it completely
            horizontalLineHeight: '64px', // Matches default header height to prevent layout shifts
            activeBarHeight: 0,           // Removes the underline height on hover/active completely
            activeBarBorderWidth: 0,      // Removes the border fallback line
            
            // Optional: Keeps text color consistent on hover/selection if you want to eliminate all blue hints
            horizontalItemSelectedColor: 'rgba(0, 0, 0, 0.88)', 
            horizontalItemHoverColor: 'rgba(0, 0, 0, 0.88)',
          },
        },
      }}
    >
      <div id="layout">
        <Layout>
          <Header className="app-header">
            <div className="header-left">
              <DesktopOutlined style={{ fontSize: 24 }} />
              <span className="app-title">Spring Boot</span>
            </div>
            <div className="header-right">
              <Menu
                mode="horizontal"
                selectedKeys={[location.pathname]}
                items={items}
                onClick={({ key }) => {
                  if (key === '/logout') logout()
                }}

                // prevent the horizontal items from collapsing into a dropdown
                disabledOverflow={true} // Prevents items from compressing or hiding
                overflowedIndicator={null} // Removes the three-dots dropdown icon entirely
                // Inline styles to clean up any remaining default outer borders
                style={{ borderBottom: 'none', background: 'transparent' }} 
              />
            </div>
          </Header>

          <Content>
            <Outlet />
          </Content>
        </Layout>
      </div>
    </ConfigProvider>
  )
}

export default App

// frontend_vue/src/App.vue
<template>
  <el-config-provider :locale="en">
    <div id="layout">
      <el-container>
        <el-header class="app-header">
          <div class="header-left">
            <el-icon :size="24"><Monitor /></el-icon>
            <span class="app-title">Spring Boot</span>
          </div>
          <div class="header-right">
            <el-menu
              :default-active="route.path"
              mode="horizontal"
              :ellipsis="false"
              router
            >
              <el-menu-item index="/">
                <el-icon><HomeFilled /></el-icon>
                Home
              </el-menu-item>
              <el-menu-item index="/login" v-if="! isLoggedIn">
                <el-icon><HomeFilled /></el-icon>
                Login
              </el-menu-item>
              <el-menu-item index="/dashboard" v-if="isLoggedIn">
                <el-icon><User /></el-icon>
                Dashboard
              </el-menu-item>
              <el-menu-item index="/users" v-if="isLoggedIn">
                <el-icon><User /></el-icon>
                Users
              </el-menu-item>
              <el-menu-item index="/logout" @click="logout" v-if=" isLoggedIn">
                <el-icon><User /></el-icon>
                Log Out
              </el-menu-item>
            </el-menu>
          </div>
        </el-header>

        <el-main>
          <router-view />
        </el-main>
      </el-container>
    </div>
  </el-config-provider>
</template>

<script setup lang="ts">
import { ref, onMounted, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import en from 'element-plus/es/locale/lang/en'

const route = useRoute()
const router = useRouter()
const isLoggedIn = ref(false)

// Function to check local storage auth status
function checkAuthStatus() {
  isLoggedIn.value = !!localStorage.getItem('token')
}

// Check status when app initializes
onMounted(() => {
  checkAuthStatus()
})

// Watch for route shifts to automatically recalculate the login state
watch(() => route.path, () => {
  checkAuthStatus()
})

// Global logout method
function logout() {
  localStorage.removeItem('token')
  isLoggedIn.value = false
  router.push('/login')
}
</script>

<style>
body {
  margin: 0;
  padding: 0;
  font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB', Arial, sans-serif;
}

.app-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  background-color: #545c64;
  color: #fff;
  padding: 0 20px;
}

.header-left {
  display: flex;
  align-items: center;
  gap: 10px;
}

.app-title {
  font-size: 20px;
  font-weight: bold;
}

.header-right .el-menu {
  background-color: transparent;
  border-bottom: none;
}

.header-right .el-menu-item {
  color: #fff;
  border-bottom: none;
}

.header-right .el-menu-item:hover,
.header-right .el-menu-item.is-active {
  background-color: transparent;
  color: #ffd04b;
  border-bottom: none;
}
</style>
