// frontend_nextjs/src/app/users/page.tsx
'use client'

import { useEffect, useState } from 'react'
import { Button, Card, Form, Input, message, Modal, Select, Table, Tag, Tooltip, App } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { DeleteOutlined, EditOutlined, PlusOutlined } from '@ant-design/icons'
import { createUser, deleteUser, getUsers, updateUser } from '@/lib/api'
import type { User, UserRequest } from '@/types'

function formatDate(dateStr: string): string {
  if (!dateStr) return ''
  const date = new Date(dateStr)
  return date.toLocaleString()
}

export default function UsersPage() {
  const [users, setUsers] = useState<User[]>([])
  const [loading, setLoading] = useState(false)
  const [dialogVisible, setDialogVisible] = useState(false)
  const [isEdit, setIsEdit] = useState(false)
  const [editingId, setEditingId] = useState(0)
  const [submitting, setSubmitting] = useState(false)
  const [form] = Form.useForm<UserRequest>()
  const [isMounted, setIsMounted] = useState(false)

  const { message, modal } = App.useApp() 

  async function fetchUsers() {
    setLoading(true)
    try {
      const res = await getUsers()
      setUsers(res.data)
    } catch (err: any) {
      message.error(err.message || 'Failed to fetch users')
    } finally {
      setLoading(false)
    }
  }

  function handleAdd() {
    setIsEdit(false)
    setEditingId(0)
    form.setFieldsValue({ username: '', email: '', role: 'USER' })
    setDialogVisible(true)
  }

  function handleEdit(row: User) {
    setIsEdit(true)
    setEditingId(row.id)
    form.setFieldsValue({ username: row.username, email: row.email, role: row.role })
    setDialogVisible(true)
  }

  function handleDelete(row: User) {
    modal.confirm({
      title: 'Confirm Delete',
      content: `Are you sure you want to delete user "${row.username}"?`,
      okText: 'Delete',
      okType: 'danger',
      cancelText: 'Cancel',
      async onOk() {
        try {
          await deleteUser(row.id)
          message.success('User deleted successfully')
          await fetchUsers()
        } catch (err: any) {
          message.error(err.message || 'Failed to delete user')
        }
      },
    })
  }

  async function submitForm() {
    const values = await form.validateFields().catch(() => null)
    if (!values) return

    setSubmitting(true)
    try {
      if (isEdit) {
        await updateUser(editingId, values)
        message.success('User updated successfully')
      } else {
        await createUser(values)
        message.success('User created successfully')
      }
      setDialogVisible(false)
      await fetchUsers()
    } catch (err: any) {
      message.error(err.message || 'Operation failed')
    } finally {
      setSubmitting(false)
    }
  }

  useEffect(() => {
    fetchUsers()
  }, [])

  useEffect(() => {
    setIsMounted(true)
  }, [])

  const columns: ColumnsType<User> = [
    { title: 'ID', dataIndex: 'id', width: 80, align: 'center' },
    { title: 'Username', dataIndex: 'username', width: 150 },
    { title: 'Email', dataIndex: 'email', width: 220 },
    {
      title: 'Role',
      dataIndex: 'role',
      width: 120,
      align: 'center',
      render: (role: string) => <Tag color={role === 'ADMIN' ? 'red' : 'default'}>{role}</Tag>,
    },
    {
      title: 'Created At',
      dataIndex: 'createdAt',
      width: 200,
      render: (value: string) => formatDate(value),
    },
    {
      title: 'Actions',
      fixed: 'right',
      width: 200,
      align: 'center',
      render: (_, row) => {
        const isDefaultAccount = [1, 2].includes(Number(row.id))
        return (
          <>
            <Tooltip title={isDefaultAccount ? 'Cannot edit default testing account' : ''}>
              <Button
                type="primary"
                size="small"
                icon={<EditOutlined />}
                disabled={isDefaultAccount}
                onClick={() => handleEdit(row)}
                style={{ marginRight: 8 }}
              >
                Edit
              </Button>
            </Tooltip>
            <Tooltip title={isDefaultAccount ? 'Cannot delete default testing account' : ''}>
              <Button
                danger
                size="small"
                icon={<DeleteOutlined />}
                disabled={isDefaultAccount}
                onClick={() => handleDelete(row)}
              >
                Delete
              </Button>
            </Tooltip>
          </>
        )
      },
    },
  ]

  return (
    <div className="user-container">
      <Card
        hoverable
        title={<span style={{ fontSize: 18, fontWeight: 'bold' }}>User Management</span>}
        extra={
          <Button type="primary" icon={<PlusOutlined />} onClick={handleAdd}>
            Add User
          </Button>
        }
      >
        <Table<User> rowKey="id" dataSource={users} columns={columns} loading={loading} bordered pagination={false} />
      </Card>

      {isMounted && (
        <Modal
          title={isEdit ? 'Edit User' : 'Add User'}
          open={dialogVisible}
          width={500}
          destroyOnHidden
          forceRender
          onCancel={() => setDialogVisible(false)}
          footer={[
            <Button key="cancel" onClick={() => setDialogVisible(false)}>
              Cancel
            </Button>,
            <Button key="submit" type="primary" loading={submitting} onClick={submitForm}>
              {isEdit ? 'Update' : 'Create'}
            </Button>,
          ]}
        >
          <Form form={form} labelCol={{ span: 6 }} labelAlign="right" initialValues={{ role: 'USER' }}>
            <Form.Item
              label="Username"
              name="username"
              rules={[
                { required: true, message: 'Please enter username' },
                { min: 2, max: 50, message: 'Username must be 2-50 characters' },
              ]}
            >
              <Input placeholder="Enter username" />
            </Form.Item>
            <Form.Item
              label="Email"
              name="email"
              rules={[
                { required: true, message: 'Please enter email' },
                { type: 'email', message: 'Please enter a valid email' },
              ]}
            >
              <Input placeholder="Enter email" />
            </Form.Item>
            <Form.Item label="Role" name="role" rules={[{ required: true, message: 'Please select role' }]}>
              <Select
                placeholder="Select role"
                options={[
                  { label: 'User', value: 'USER' },
                  { label: 'Admin', value: 'ADMIN' },
                ]}
              />
            </Form.Item>
          </Form>
        </Modal>
      )}
    </div>
  )
}

// frontend_angular/src/app/features/users/users.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatTableModule } from '@angular/material/table';
import { MatChipsModule } from '@angular/material/chips';
import { MatTooltipModule } from '@angular/material/tooltip';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { MatDialog, MatDialogModule } from '@angular/material/dialog';
import { MatSnackBar } from '@angular/material/snack-bar';
import { User, UserRequest } from '../../core/models/user.model';
import { UserService } from '../../core/services/user.service';
import { UserFormDialogComponent, UserFormDialogData } from './user-form-dialog.component';
import { ConfirmDialogComponent } from './confirm-dialog.component';

@Component({
  selector: 'app-users',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatButtonModule,
    MatIconModule,
    MatTableModule,
    MatChipsModule,
    MatTooltipModule,
    MatProgressBarModule,
    MatDialogModule,
  ],
  templateUrl: './users.component.html',
  styleUrl: './users.component.css',
})
export class UsersComponent implements OnInit {
  private readonly userService = inject(UserService);
  private readonly dialog = inject(MatDialog);
  private readonly snackBar = inject(MatSnackBar);

  users: User[] = [];
  loading = false;
  displayedColumns = ['id', 'username', 'email', 'role', 'createdAt', 'actions'];

  ngOnInit(): void {
    this.fetchUsers();
  }

  formatDate(dateStr: string): string {
    if (!dateStr) return '';
    return new Date(dateStr).toLocaleString();
  }

  isProtected(id: number): boolean {
    return [1, 2].includes(Number(id));
  }

  fetchUsers(): void {
    this.loading = true;
    this.userService.getUsers().subscribe({
      next: (res) => {
        this.users = res.data;
        this.loading = false;
      },
      error: (err) => {
        this.notify(err.message || 'Failed to fetch users');
        this.loading = false;
      },
    });
  }

  handleAdd(): void {
    const ref = this.dialog.open<UserFormDialogComponent, UserFormDialogData, UserRequest>(
      UserFormDialogComponent,
      { width: '500px', data: { isEdit: false } }
    );

    ref.afterClosed().subscribe((result) => {
      if (!result) return;
      this.userService.createUser(result).subscribe({
        next: () => {
          this.notify('User created successfully');
          this.fetchUsers();
        },
        error: (err) => this.notify(err.message || 'Operation failed'),
      });
    });
  }

  handleEdit(row: User): void {
    const ref = this.dialog.open<UserFormDialogComponent, UserFormDialogData, UserRequest>(
      UserFormDialogComponent,
      { width: '500px', data: { isEdit: true, user: row } }
    );

    ref.afterClosed().subscribe((result) => {
      if (!result) return;
      this.userService.updateUser(row.id, result).subscribe({
        next: () => {
          this.notify('User updated successfully');
          this.fetchUsers();
        },
        error: (err) => this.notify(err.message || 'Operation failed'),
      });
    });
  }

  handleDelete(row: User): void {
    const ref = this.dialog.open(ConfirmDialogComponent, {
      width: '420px',
      data: {
        title: 'Confirm Delete',
        message: `Are you sure you want to delete user "${row.username}"?`,
      },
    });

    ref.afterClosed().subscribe((confirmed) => {
      if (!confirmed) return;
      this.userService.deleteUser(row.id).subscribe({
        next: () => {
          this.notify('User deleted successfully');
          this.fetchUsers();
        },
        error: (err) => this.notify(err.message || 'Failed to delete user'),
      });
    });
  }

  private notify(message: string): void {
    this.snackBar.open(message, 'Close', { duration: 3000 });
  }
}

<div class="user-container">
  <mat-card appearance="raised">
    <mat-card-header>
      <mat-card-title class="card-header">
        <span style="font-size: 18px; font-weight: bold">User Management</span>
        <button mat-raised-button color="primary" (click)="handleAdd()">
          <mat-icon>add</mat-icon>
          Add User
        </button>
      </mat-card-title>
    </mat-card-header>

    <mat-card-content>
      <mat-progress-bar *ngIf="loading" mode="indeterminate"></mat-progress-bar>

      <table mat-table [dataSource]="users" class="mat-elevation-z1 users-table">
        <ng-container matColumnDef="id">
          <th mat-header-cell *matHeaderCellDef>ID</th>
          <td mat-cell *matCellDef="let row">{{ row.id }}</td>
        </ng-container>

        <ng-container matColumnDef="username">
          <th mat-header-cell *matHeaderCellDef>Username</th>
          <td mat-cell *matCellDef="let row">{{ row.username }}</td>
        </ng-container>

        <ng-container matColumnDef="email">
          <th mat-header-cell *matHeaderCellDef>Email</th>
          <td mat-cell *matCellDef="let row">{{ row.email }}</td>
        </ng-container>

        <ng-container matColumnDef="role">
          <th mat-header-cell *matHeaderCellDef>Role</th>
          <td mat-cell *matCellDef="let row">
            <mat-chip [class.role-admin]="row.role === 'ADMIN'" [class.role-user]="row.role !== 'ADMIN'">
              {{ row.role }}
            </mat-chip>
          </td>
        </ng-container>

        <ng-container matColumnDef="createdAt">
          <th mat-header-cell *matHeaderCellDef>Created At</th>
          <td mat-cell *matCellDef="let row">{{ formatDate(row.createdAt) }}</td>
        </ng-container>

        <ng-container matColumnDef="actions">
          <th mat-header-cell *matHeaderCellDef style="text-align: center">Actions</th>
          <td mat-cell *matCellDef="let row" style="text-align: center">
            <button
              mat-button
              color="primary"
              [disabled]="isProtected(row.id)"
              [matTooltip]="isProtected(row.id) ? 'Cannot edit default testing account' : ''"
              [matTooltipDisabled]="!isProtected(row.id)"
              (click)="handleEdit(row)"
            >
              <mat-icon>edit</mat-icon>
              Edit
            </button>
            <button
              mat-button
              color="warn"
              [disabled]="isProtected(row.id)"
              [matTooltip]="isProtected(row.id) ? 'Cannot delete default testing account' : ''"
              [matTooltipDisabled]="!isProtected(row.id)"
              (click)="handleDelete(row)"
            >
              <mat-icon>delete</mat-icon>
              Delete
            </button>
          </td>
        </ng-container>

        <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
        <tr mat-row *matRowDef="let row; columns: displayedColumns; let i = index" [class.stripe]="i % 2 === 1"></tr>
      </table>
    </mat-card-content>
  </mat-card>
</div>
